---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: birthday
  username: merb
  password: merb
  host:     localhost
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: birthday-test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: birthday-production
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults
